services:
  db:
    image: mysql:8.0
    container_name: db
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: PROD
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always

  api:
    build: .
    container_name: api
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    restart: always

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - api
    restart: always

volumes:
  mysql_data:
