services:
  api:
    build: .
    container_name: api
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    restart: always

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - api
    restart: always

volumes:
  mysql_data:
