name: Dev Deployment

on:
  push:
    branches: ["dev"]

env:
  AWS_REGION: ap-northeast-2
  ECR_REPOSITORY: APPO_API
  APP_NAME: APPO
# 테스트 서버 확보 후 배포 Workflow로 변경 요망
jobs:
  linter:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install Poetry
        if: steps.cache-poetry.outputs.cache-hit != 'true'
        run: |
          curl -sSL https://install.python-poetry.org | python3 -

      - name: Install dependencies
        if: steps.cache-poetry.outputs.cache-hit != 'true'
        run: |
          poetry install

      - name: Run linters
        run: |
          poetry run pre-commit run --all-files
